"""Default bilingual rules for interest scoring."""

from __future__ import annotations

DEFAULT_TERM_RANGES: dict[int, dict[str, set[str]]] = {
    25: {
        "es": {
            "burocracia",
            "cotilleos",
            "economía",
            "estrategia",
            "finanzas",
            "fútbol",
            "guerras",
            "impuestos",
            "política",
            "religión",
        },
        "en": {
            "bureaucracy",
            "economy",
            "finance",
            "football",
            "gossip",
            "politics",
            "religion",
            "strategy",
            "taxes",
            "wars",
        },
    },
    50: {
        "es": {
            "aprender",
            "coches",
            "dibujos animados",
            "física",
            "geografía",
            "historia",
            "idiomas",
            "literatura",
            "matemáticas",
            "videojuegos",
        },
        "en": {
            "cartoons",
            "cars",
            "geography",
            "history",
            "languages",
            "learning",
            "literature",
            "mathematics",
            "physics",
            "video games",
        },
    },
    75: {
        "es": {
            "ciencia ficción",
            "cine",
            "electrónica",
            "espacio",
            "los vengadores",
            "mecánica",
            "moda",
            "motor",
            "música",
            "teatro",
            "viajes",
        },
        "en": {
            "cinema",
            "electronics",
            "engines",
            "fashion",
            "mechanics",
            "movies",
            "music",
            "science fiction",
            "space",
            "the avengers",
            "theater",
            "travel",
        },
    },
    100: {
        "es": {
            "animales",
            "emociones",
            "inteligencia artificial",
            "interacción social",
            "investigación",
            "pilates",
            "programación",
            "psicología",
            "robótica",
            "tecnología",
        },
        "en": {
            "animals",
            "artificial intelligence",
            "emotions",
            "pilates",
            "programming",
            "psychology",
            "research",
            "robotics",
            "social interaction",
            "technology",
        },
    },
}

DEFAULT_REGEX_RANGES: dict[int, dict[str, tuple[str, ...]]] = {}

DEFAULT_IGNORE_WORDS: dict[str, set[str]] = {
    "es": {
        "a",
        "ante",
        "bajo",
        "con",
        "contra",
        "de",
        "desde",
        "durante",
        "el",
        "en",
        "entre",
        "es",
        "excepto",
        "hacia",
        "hasta",
        "la",
        "las",
        "los",
        "me",
        "mediante",
        "o",
        "para",
        "por",
        "segun",
        "si",
        "sin",
        "sobre",
        "tras",
        "un",
        "una",
        "unas",
        "unos",
        "y",
        "yo",
    },
    "en": {
        "a",
        "about",
        "an",
        "and",
        "at",
        "for",
        "from",
        "i",
        "in",
        "is",
        "it",
        "me",
        "my",
        "of",
        "on",
        "or",
        "the",
        "to",
        "with",
    },
}

SPANISH_SUFFIXES = (
    "iendo",
    "ando",
    "ado",
    "ido",
    "ar",
    "er",
    "ir",
    "as",
    "os",
    "es",
    "s",
    "a",
    "o",
    "e",
)

ENGLISH_SUFFIXES = (
    "ing",
    "ed",
    "ies",
    "es",
    "s",
)
